import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import About from "./components/About";
import Navbar from "./components/Navbar";
import Presentation from "./components/Presentation";
import { useState } from "react";

export default function Home() {

  const [language, setlanguage] = useState(false);

  const changeLanguage=()=>{
    setlanguage(!language)
  }

  const dataEs={
    nav:{
      a1:"inicio",
      a2:"acerca",
      a3:"proyectos",
      icon:"/usa.png"
    },
    about:{
      title:"Acerca de mi",
      subtitle1:"Quien soy",
      subtitle2:"Habilidades",
      p1:"Andrés Agudelo, Tecnólogo en sistemas.",
      p2:"Desarrollador Front-end, apasionado por aprender y crear nuevas cosas.",
      btn:"Ver hoja de vida",
    }
  }

  const dataEn={
    nav:{
      a1:"home",
      a2:"about",
      a3:"projects",
      icon:"/col.png "
    },
    about:{
      title:"About me",
      subtitle1:"Who I am",
      subtitle2:"Skills",
      p1:"Andrés Agudelo, Systems Technologist.",
      p2:"Front-end developer, passionate about learning and creating new things.",
      btn:"See CV",
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar setLanguage={changeLanguage} data={language?dataEs:dataEn}/>
      <Presentation />
      <About data={language?dataEs:dataEn}/>
    </div>
  );
}
