import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import About from "./components/About";
import Navbar from "./components/Navbar";
import Presentation from "./components/Presentation";
import { useState } from "react";
import Projects from "./components/Projects";
import { dataEs, dataEn } from "./components/data";
import Footer from "./components/Footer";

export default function Home() {
  const [language, setlanguage] = useState(false);

  const changeLanguage = () => {
    setlanguage(!language);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar setLanguage={changeLanguage} data={language ? dataEs : dataEn} />
      <Presentation />
      <About data={language ? dataEs : dataEn} />
      <Projects projects={language ? dataEs : dataEn} />
      <Footer/>
    </div>
  );
}
