import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import About from "./components/About";
import Navbar from "./components/Navbar";
import Presentation from "./components/Presentation";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Portafolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <Presentation />
      <About />
    </div>
  );
}
